name: example
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0-0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
#  firebase: ^9.0.3
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  cloud_firestore: ^4.8.2
  font_awesome_flutter: ^10.5.0
  get: ^4.6.6
  http: ^1.2.1
  convert:
  google_fonts:
  sqflite: ^2.3.3
  file_picker: ^8.0.1
  image_picker: ^1.1.0
  open_filex: ^4.4.0
  chatview:
    path: ../
  firebase_messaging: ^14.9.1
  flutter_custom_clippers: ^2.1.0
  firebase_storage: ^11.7.5
  firebase_app_check: ^0.2.2+5
#  firebase_messaging: ^14.9.1
#  firebase_analytics: ^10.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true
  assets:
    - image/1.jpg
    - image/2.jpg
    - image/3.jpg
    - image/back/4.jpg
    - image/back/backg.jpg
    - image/unkown.png
    - image/