// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyqt7_5DanKlgFgdCNxv-wdm0N5n5c-Hw',
    appId: '1:82580526912:web:bc9fb0fd5989ebf8fecca5',
    messagingSenderId: '82580526912',
    projectId: 'chat-app-9e8cb',
    authDomain: 'chat-app-9e8cb.firebaseapp.com',
    storageBucket: 'chat-app-9e8cb.appspot.com',
    measurementId: 'G-4W5PQDW6R8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCz258WcvVVjzRYe5PbuD19JBmGiOYrYM',
    appId: '1:82580526912:android:48e6e518aee3d430fecca5',
    messagingSenderId: '82580526912',
    projectId: 'chat-app-9e8cb',
    storageBucket: 'chat-app-9e8cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsJBFi8477eNmhOuDPdf5A7GiVD_q7tXk',
    appId: '1:82580526912:ios:0db217ce503273a2fecca5',
    messagingSenderId: '82580526912',
    projectId: 'chat-app-9e8cb',
    storageBucket: 'chat-app-9e8cb.appspot.com',
    iosBundleId: 'com.chatview.example',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsJBFi8477eNmhOuDPdf5A7GiVD_q7tXk',
    appId: '1:82580526912:ios:681d7dba5c53e00ffecca5',
    messagingSenderId: '82580526912',
    projectId: 'chat-app-9e8cb',
    storageBucket: 'chat-app-9e8cb.appspot.com',
    iosBundleId: 'com.example.example',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAyqt7_5DanKlgFgdCNxv-wdm0N5n5c-Hw',
    appId: '1:82580526912:web:6963cffd54f47bb2fecca5',
    messagingSenderId: '82580526912',
    projectId: 'chat-app-9e8cb',
    authDomain: 'chat-app-9e8cb.firebaseapp.com',
    storageBucket: 'chat-app-9e8cb.appspot.com',
    measurementId: 'G-4BH2X91CLT',
  );
}
